-- placeable_furniture.script

if not placeable_furniture
or not placeable_furniture.pickup_obj
or not placeable_furniture.gc
then
	return
end

-- ===================================================================
--  gc （家具を拾う時のメッセージ）
-- ===================================================================
local original_translate_string = placeable_furniture.gc

placeable_furniture.gc = function(string_id, ...)
	if string_id == "Picked up object" then
		return "アイテムを拾った"
	end
	return original_translate_string(string_id, ...)
end
